# Introduction

In this notebook we will write our first set of simple Python programs, covering simple variables and types, lists strings and dictionary types. Towards the end we will discuss math operators, conditions, functions and basic input/otuput statements. 



# Structuring your code

Python uses indentation instead of braces to structure its programs and scripts into blocks.  All code within a block must be horizontally aligned such that each line starts equidistant from the left.

By blocks we refer to lines of code that are run in serial, as a group. Such that code within a loop for example will belong to a block, and a loop within a loop will require its own indentation. The below section of code provides an example of this; note that you are not, at this time, expected to understand all the specific syntatic elements. Simply observe how each each 'for' statement the code moves further to the left:


In [ ]:
#the first code block
myfirstlist=[10,20,30,40,45, 'a']
mysecondlist=[1,2,3,4,5]

for a in myfirstlist:
  print(a)
  print('Hello')

#the first code block
myfirstlist=[10,20,30,40,45, 'a']
mysecondlist=[1,2,3,4,5]

for a in myfirstlist:
  print(a)

print('Hello')

10
Hello
20
Hello
30
Hello
40
Hello
45
Hello
a
Hello
10
20
30
40
45
a
Hello


Try changing the indentation of some of the lines of code - see what happens

# Hello world

The simplest and most ubiqitous function in Python is the print function. To print a statement simply type

In [ ]:
print("Hello world")

Hello world


This typifies the simplicity of Python. In contrast, the 'Hello World' programme in C++ ; requires several lines of code, imports of standard libraries and will not run until it is compiled:

```c++
#include <iostream>
using namespace std;

int main() 
{
    cout << "Hello, World!";
    return 0;
}
```

Both these functions simply return the string 'Hello World'

# Formatted output

In some cases we will use printed statements with formatted output using the ```format``` (``` str.format ```) method for strings:

> Indented block



In [ ]:
print('{} {}'.format('hello', 'you'))

hello you


Using this formulation it is also possible to cast data types and truncate floats:


In [ ]:
# Example of print
print('My name is {} and I live in {}'.format('Vittoria', 'London'))
print('Pi {}'.format(3.14159))
print('Pi {:.2f} {:.2f} {:.2f}'.format(3.14159, 3.55567, 9.2214))
print('Pi {1:.2f} {0:.2f} {2:.2f}'.format(3.14159, 3.55567, 9.2214))

My name is Vittoria and I live in London
Pi 3.14159
Pi 3.14 3.56 9.22
Pi 3.56 3.14 9.22


The general syntax for a format placeholder is:

```[argument]:[width][.precision]type```

Such that in the above example: 0 is the position of the argument, 8 is the width (float must be formatted with 8 characters), 2 is the number of decimal places and ```f``` is the type. Examples of common types include

- ```d``` signed integer decimal e.g. an integer would be formatted as ```{5d} ```
- ```s``` string
- ```f``` floating point decimal

For more examples see https://www.python-course.eu/python3_formatted_output.php



# Commenting

It is always important to comment code such that others can read and use it. In Python there are two approaches to code commenting: 1) using ```#```

In [ ]:
# this is a code comment

# Variables and Types

# Numbers

Python supports three types of numbers:
    - integers 
    - floats
    - complex  numbers

Complex numbers will not be used in this course. An example of assigning a variable an integer value is:


In [ ]:
myint = 9
print('example integer is ', myint)

example integer is  9


Examples of float declarations are:

In [ ]:
myfloat1=9.3
myfloat2=float(9)
myfloat3=float(5)
n=5
print('example integer is ', myfloat1)
print('casting an integer as a float results in', myfloat2)
print ('numbers like {} are written as {} as floaters' .format (n, myfloat3))

example integer is  9.3
casting an integer as a float results in 9.0
numbers like 5 are written as 5.0 as floaters


In these examples ```python myint``` and ```python myfloat``` are examples of variables.  Python is not "statically typed". This means you do not need to declare variables before using them, nor declare their type. Every variable in Python is an object for example you can declare simple variables within a print statement, and do math on them without first declaring their type e.g:

In [ ]:
a=5
b=2.3
print('the sum of {} and {} is {}'.format(a,b,a+b))

the sum of 5 and 2.3 is 7.3


# Strings



```
# This is formatted as code
```

Strings are defined either with a single quote or a double quotes e.g. 

In [ ]:
string1="hello world"
string2='hello world'
print (string1)
print(string2)
print('testing if string1 and string2 are equal:', string1==string2)

hello world
hello world
testing if string1 and string2 are equal: True


If you need a apostrophe inside, format as

In [ ]:
string1="Steve's dog"
print(string1)

Steve's dog


# Operators

The basic math operators are:
- addition (```+```)
- subtraction (```-```)
- multiplication (```*```)
- division (```/``` or ```//```)

Try out some simple math operations:

In [ ]:
print('addition:', 2+3)
print('subtraction:', 2-3)
print('multiplication:', 2*3)
print('division:', 2/3)

addition: 5
subtraction: -1
multiplication: 6
division: 0.6666666666666666


The modulus operator (```%```) returns the integer remainder following division:

In [ ]:
a=9
b=5
print('the remainder following division of {} by {} is {}'.format(a, b, a%b))

the remainder following division of 9 by 5 is 4


Using ```*``` twice (```**```) results in the power operator

In [ ]:
a=2
b=4
print('{} to the power {} is {}'.format(a, b, a**b))

2 to the power 4 is 16


Operators also work on strings. You can use ```+``` and ```*``` to concatenate strings for example:

In [ ]:
string1= "ha"
print('hello'*10)
print('I write "{}" for average funny comments, "{}" for actually funny comments, and "{}" for hilarious ones' .format(string1*2, string1*3, string1*4))

hellohellohellohellohellohellohellohellohellohello
I write "haha" for average funny comments, "hahaha" for actually funny comments, and "hahahaha" for hilarious ones


Any number of variables in your python stript can be cast as strings using ```str()``` or ```{ } ``` in conjunction with ```str.format``` or in as a 'format string'

In [ ]:
a=10

# here the integer variable a is cast as a string; otherwise python automatically assumes it is an int
print('hello'+str(a)) 
print(f'hello{a}') # format string - note 'f
print('hello{}'.format(a) )

hello10
hello10
hello10


# Conditions

Conditions containing boolean operators ``` == > < ``` are formatted as:

In [ ]:
a=10
print(a==10)
print(a<12)
print(a>20)

True
True
False


Two conditional statements can be considered concurrent with ```and,or, and is``` statements

In [ ]:
a=10
b=12
print(a is b)
print(a< 15 and b > 10)
print (a < 15 or b < 10)

False
True
True


Using "not" before a boolean expression inverts it:

In [ ]:
print(not a is b)

True


# Exercise: Variables, Operators and Conditions

Ex 1. Playing with the print function and string formatting 

In [ ]:
# Complete Ex 1 below; responding below each comment block

# Q1 define variables
#e.g. a=5; b=10; teststr='Hello World'

# Q2 Practice print statements e.g. print('hello world')

# Q3 Try printing the variable teststr (what if you change to double quotes)

# Q4 Try adding the variable 'a' to variable 'teststr' within a print statement 
#   (there are 3 ways of doing this, try all)

Hello Wolrd
a=5 and b=10
I will never understand it
Hello Wolrd
Hello Wolrd 5
Hello Wolrd 5
Hello Wolrd 5


Ex 2. Try some simple operations

In [ ]:
# Complete Ex 2 below; responding below each comment 

# Q1 attempt simple simple math operations, print the output (Hint - uncomment and complete)
a=1
b=2

#print(' a -b = ', )
#print(' a*b = ', )
#print(' a/b = ', )

# Q2 combinations of math operators try combining math operators e.g. a*a+b - a/b 

# Q3 what happens through the addition of brackets e.g. a*(a+b - a/b) or (a*a+b - a)/b 

Ex 3. Experiment with Conditions

In [ ]:
# Complete Ex 3 below; responding below each comment 

# Q1 define variables (completed for you)

a=5
b=10
teststr1='Hello'
teststr2='World'

# Q2 complete and evaluate the following conditional statements
print('a==b',)
print('2*a==b is',)
print('a>b',)
print('a<b',)
print('a is b',)
print('2*a is b',)

# Q3 combine statements using and/or statements e.g. 'a == b or b> a'; 
#try different combinations; print out

# Q4 try inverting your previous statements with a not;

# Q5 what happens when you negate a statement joined by an 'and' ;

# Q6 what if you add nots before both statements?


a==b
2*a==b is
a>b
a<b
a is b
2*a is b


# Lists

A list is an ordered collection of objects. List elements don't have to be of the same type but can be an arbitrary mixture of numbers, strings, or other types of objects. Lists can contain other lists as sub-lists. Examples of lists:

In [ ]:
emptylist=[] # An empty list
integerlist=[1,2,3,4,5,6] #A list of integers
stringlist=['string1', 'string2', 'string3'] #A list of strings
mixedlist=[10, "some string", 4.2, 2, 'some other string'] #A list of mixed data types
# a nested list  - note sublists are not same lengths
nestedlist=[['dog','cat','pig'], [1,2,3 ,4], [10, "some string", 4.2, 2, 'some other string'] ]

## Indexing sequential data types

Lists, and strings are what as known as sequential data types. This means that they can be manipulated in ways similar to arrays in Matlab and C++. Please that matrices and numeric arrays will be dealt with separately through the use of the Numpy package, towards the end of this week's lectures.

As array-like objects, this means that it is possible to index and slice different elements or groups of elements from strings and lists. For examples, using the list object's defined above:

In [ ]:
teststr='Hello World'
print('the third element of the integer list', integerlist[2])
print('the fourth element of the mixed list', mixedlist[3])
print('the seventh element of the string', teststr[6])

the third element of the integer list 3
the fourth element of the mixed list 2
the seventh element of the string W


** <font color='red'> NOTE in python all array like objects are indexed from 0 not 1 (like Matlab)  </font>  **

Indexing can also be done in reverse:

In [ ]:
print('the last element of the integer list', integerlist[-1])

the last element of the integer list 6


We can slice different elements of lists:

In [ ]:
# note slice indexing takes all elements upto but not including the last index 
print('the middle two elements of the integer list', integerlist[2:4])
#slicing from the beginning to element 5
print('the middle two elements of the integer list', integerlist[:5])
#slicing from element 5 to the end
print('the middle two elements of the integer list', integerlist[4:])
#slicing from element 5 to one from the end
print('the middle two elements of the integer list', integerlist[4:-1])

the middle two elements of the integer list [3, 4]
the middle two elements of the integer list [1, 2, 3, 4, 5]
the middle two elements of the integer list [5, 6]
the middle two elements of the integer list [5]


We can also check whether elements are within a list using ```in```:

In [ ]:
print('is 3 in integer list?', 3 in integerlist)

is 3 in integer list? True


## Assignment and Mutation

It is possible to increase the length of a list using ```append()```

In [ ]:
emptylist=[] # An empty list
integerlist=[1,2,3,4,5,6] #A list of integers
integerlist.append(7)
print('new integer list', integerlist)
integerlist

new integer list [1, 2, 3, 4, 5, 6, 7]


[1, 2, 3, 4, 5, 6, 7]

Incidentally the lengths of strings and lists can be determined using ```len()```:

In [ ]:
print('the length of the new integer list is', len(integerlist))
print('the length of the teststr is', len(teststr))

the length of the new integer list is 7
the length of the teststr is 11


Lists can be added together like strings:

In [ ]:
print(integerlist+stringlist)

[1, 2, 3, 4, 5, 6, 7, 'string1', 'string2', 'string3']


Items of lists can be swapped out for new ones:

In [ ]:
stringlist[2]=3
print(stringlist)

['string1', 'string2', 3]


This makes lists _**Mutable**_ objects. On the other hand string are _**Immutable**_; you cannot change them once created. Try running the following line of code and see what happens

In [ ]:
teststr='Hello World'
newstring= 'New' + ' ' + teststr[6:]
print(newstring)

New World


### Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 



**Arrays** 

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
import numpy as np

# Create a rank 1 array
a = np.array([1, 2, 3])   
print(type(a))            
print(a.shape)            
print(a[0], a[1], a[2])   
# Change an element of the array
a[0] = 5                  
print(a)                 
# Create a rank 2 array
b = np.array([[1,2,3],[4,5,6]])   
print(b) 
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   


c = np.array ([[1, 2, 3], [4,5,6], [7,8, 9]])
print(c)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Numpy also provides many functions to create arrays:


In [ ]:
import numpy as np

# Create a 2x2 array of all zeros
a = np.zeros((2,2))   
print(a)             

# Create a 1x2 array of all ones
b = np.ones((1,2))    
print(b)              

# Create a 2x2 constant array
c = np.full((2,2), 7)  
print(c)              

# Create a 2x2 identity matrix
d = np.eye(2)         
print(d)              

# Create a 2x2 array filled with random values
e = np.random.random((2,2))  
print(e)                    

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.63467179 0.84991332]
 [0.36824641 0.29128088]]


**Array indexing**

Numpy offers several ways to index into arrays.

Similar to lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:



In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 2 and 3
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])
print(b[0, 1])    
b[0, 0] = 77     
print(b)  
print (a) 


[[2 3]
 [6 7]]
2
3
[[77  3]
 [ 6  7]]
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. 



In [ ]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape) 
print ("stop") 
print(row_r2, row_r2.shape) 
print ("stop") 

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  
print ("stop")
print(col_r2, col_r2.shape)  
print ("stop")

[5 6 7 8] (4,)
stop
[[5 6 7 8]] (1, 4)
stop
[ 2  6 10] (3,)
stop
[[ 2]
 [ 6]
 [10]] (3, 1)
stop


**Boolean array indexing**

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.



In [ ]:
import numpy as np

a = np.array([[0,5], [3, 1], [5, 2]])

# Find the elements of a that are bigger than 2; this returns a numpy array of Booleans of the same 
# shape as a, where each slot of bool_idx tells whether that element of a is > 2.
bool_idx = (a > 2)   

print(bool_idx)     

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  

# We can do all of the above in a single concise statement:
print(a[a > 2])     

[[False  True]
 [ True False]
 [ True False]]
[5 3 5]
[5 3 5]


# Tuples

Tuples are immutable lists. They are defined analogously to lists, except that the set of elements is enclosed in parentheses instead of square brackets:

In [ ]:
mytuple=(10,"Dog's", 4.2)
print('My tuple index 2:', mytuple[1])

My tuple index 2: Dog's


Use of tuples can be advantageous in some cases as they are faster to index than lists, and can be useful in cases where you know you want to permanently fix the items in that list

# Dictionaries

In many ways dictionaries are similar to lists: they can contain any type of object, be easily changed, and appended at run time. However unlike lists Dictionaries are unordered, indexed instead using keys

In [ ]:
mydict={}
mydict['Name']='Dave'
mydict['Age']=23
mydict['job']='Lecturer'
mydict['height']=190

Dictionaries can be contained in lists and lists in Dictionaries. Any immutable type can be used as keys in dictionaries i.e. strings, ints floats tuples. 

In [ ]:
mydict[5]='val1'
mydict[3.2413]='val2'
mydict[(1,2,3)]='val3'

What happens, if we try to access a key, i.e. a city, which is not contained in the dictionary? We raise a ```KeyError:```

In [ ]:
mydict['height']

190

As dictionaries are unordered it is impossible to index by number

In [ ]:
mydict[0]

KeyError: ignored

Otherwise many of the same functions that operate on lists, operate on dictionaries:

In [ ]:
print('My dictionary length:' ,len(mydict))
print("Is key 'Name' in my dictionary" ,'name' in mydict) # note this is case sensitive; try changing 'Name' to 'name'

My dictionary length: 7
Is key 'Name' in my dictionary False


Dictionary elements can be deleted using ```del mydict[key]```

In [ ]:
del mydict['Name']
print('Now my dictionary length:',len(mydict))



Now my dictionary length: 6


# Exercise: Dictionaries and Lists

Ex 1. Lists:

    - Create an list of integers
    - Estimate the length of the list; print it out
    - Index the list at different points along its length
    - Take a slice of a subset of elements from the list
    - Append the list with a new item of a different type

In [ ]:
#Ex1. e.g. mylist=[1,2,3,4,5]


Ex 2. Operations on sequential data types

    - Concatenate two strings, and two lists 
    - Concatenate 10 copies of each string

In [ ]:
#Ex2

string1='Hello'
string2='World'
list1=['Hello', 'World']
list2=["I'm", 'ready', 'to' 'Python']

# Important - Never name your variables after data types i.e. str='mystring', list=['some', 'list'] should never be used 

# Q1 Concatenate two strings, and two lists 

# Q2  Concatenate 10 copies of each string


Ex 3. Mutable and Immutable objects

    - Try changing different elements of this string and list
    - Create a tuple, try to change 

In [ ]:
#Ex3

mylist=['Is', 'this' ,'list' ,'mutable']
mystring='Is this string Mutable'

# change element 3 of mylist

#change element 2 of mystring


['Is', 'this', 'story', 'mutable']


Ex 4. Create a dictionary that translates english to French (or any other language); what other uses for dictionaries can you think of?

In [ ]:
# Ex4 


Ex5. Write a Python program to sort a given dictionary by key

In [ ]:
# Ex5 
color_dict = {'red':'#FF0000',
          'green':'#008000',
          'black':'#000000',
          'white':'#FFFFFF'}
